name: Update Clash dashboard
on:
  workflow_dispatch:
  schedule:
    - cron: "30 16 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@main

    - name: ClashPremium-latest
      run: |
        mkdir -p ./tmp/ClashPremium-latest/
        curl -o ./tmp/upx.tar.xz -L https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-amd64_linux.tar.xz
        tar -xf ./tmp/upx.tar.xz -C ./tmp/
        rm -f ./ClashPremium-latest/*.tar.gz
        cp -f ./ClashPremium-latest/* ./tmp/ClashPremium-latest/
        archs=(amd64 armv5 armv6 armv7 armv8 mips-softfloat mipsle-hardfloat mipsle-softfloat)
        for((i=0;i<7;i++)); do
          ./tmp/upx-4.2.2-amd64_linux/upx -d ./ClashPremium-latest/clashpremium-linux-${archs[i]}
          mv -f ./ClashPremium-latest/clashpremium-linux-${archs[i]} ./ClashPremium-latest/CrashCore
          tar -czf ./ClashPremium-latest/clashpremium-linux-${archs[i]}.tar.gz -C ./ClashPremium-latest/ ./CrashCore
        done
        cp -f ./tmp/ClashPremium-latest/* ./ClashPremium-latest/
        rm -rf ./tmp*

    - name: ClashPremium-latest
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add . && git commit -m "Clash Premium 内核 Latest 版" || exit 0
        git push -f

    - name: ClashPremium-release
      run: |
        mkdir -p ./tmp/ClashPremium-release/
        curl -o ./tmp/upx.tar.xz -L https://github.com/upx/upx/releases/download/v4.2.2/upx-4.2.2-amd64_linux.tar.xz
        tar -xf ./tmp/upx.tar.xz -C ./tmp/
        rm -f ./ClashPremium-release/*.tar.gz
        cp -f ./ClashPremium-release/* ./tmp/ClashPremium-release/
        archs=(amd64 armv5 armv6 armv7 armv8 mips-softfloat mipsle-hardfloat mipsle-softfloat)
        for((i=0;i<7;i++)); do
          ./tmp/upx-4.2.2-amd64_linux/upx -d ./ClashPremium-release/clashpremium-linux-${archs[i]}
          mv -f ./ClashPremium-release/clashpremium-linux-${archs[i]} ./ClashPremium-release/CrashCore
          tar -czf ./ClashPremium-release/clashpremium-linux-${archs[i]}.tar.gz -C ./ClashPremium-release/ ./CrashCore
        done
        cp -f ./tmp/ClashPremium-release/* ./ClashPremium-release/
        rm -rf ./tmp*

    - name: ClashPremium-latest
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add . && git commit -m "Clash Premium 内核 Release 版" || exit 0
        git push -f

    - name: Purge jsDelivr CDN
      run: |
        cd ./ClashPremium-latest/ || exit 1
        for file in $(ls); do
          curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@main/ClashPremium-latest/${file}"
        done
        cd ../ClashPremium-release/ || exit 1
        for file in $(ls); do
          curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@main/ClashPremium-release/${file}"
        done
