name: Update Clash.Meta Release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".github/workflows/delete-old-workflows.yml"
      - ".github/workflows/update-adguardhome-prerelease.yml"
      - ".github/workflows/update-adguardhome-release.yml"
      - ".github/workflows/update-clash.meta-alpha.yml"
      - ".github/workflows/update-clashdashboard.yml"
      - ".github/workflows/update-clashpremium-latest.yml"
      - ".github/workflows/update-clashpremium-release.yml"
      - ".github/workflows/update-singbox-prerelease.yml"
      - ".github/workflows/update-singbox-puernya.yml"
      - ".github/workflows/update-singbox-release.yml"

jobs:
  go:
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.go.outputs.version}}
    steps:
      - name: Get `Go` latest version
        id: go
        run: |
          echo version=$(curl -s https://raw.githubusercontent.com/actions/go-versions/update-versions-manifest-file/versions-manifest.json | grep -oE '"version": "[0-9]{1}.[0-9]{1,}(.[0-9]{1,})?"' | head -1 | cut -d':' -f2 | sed 's/ //g; s/"//g') >> $GITHUB_OUTPUT

  meta:
    runs-on: ubuntu-latest
    needs: go
    outputs:
      version: ${{steps.meta.outputs.version}}
      tags: ${{steps.meta.outputs.tags}}
    steps:
      - name: Checkout meta
        uses: actions/checkout@v4
        with:
          repository: MetaCubeX/mihomo
          ref: Meta
          fetch-depth: 0

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{needs.go.outputs.version}}

      - name: Get `meta` version
        id: meta
        run: |
          version=$(curl -sSL https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | grep 'tag_name' | sed 's/.*v/v/g' | sed 's/",$//g')
          echo version=$version >> $GITHUB_OUTPUT
          echo tags=$TAGS >> $GITHUB_OUTPUT

  cross:
    strategy:
      matrix:
        include:
          # Windows
          - name: windows-amd64
            goos: windows
            goarch: amd64
            goamd64: v3

      fail-fast: false
    runs-on: ubuntu-latest
    needs:
      - go
      - meta
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOAMD64: ${{ matrix.goamd64 }}
      GOARM: ${{ matrix.goarm }}
      GOMIPS: ${{ matrix.gomips }}
      CGO_ENABLED: 0
      TAGS: ${{needs.meta.outputs.tags}}
      VERSION: ${{needs.meta.outputs.version}}
    steps:
      - name: Checkout meta
        uses: actions/checkout@v4
        with:
          repository: MetaCubeX/mihomo
          ref: Meta
          fetch-depth: 1

      - name: Setup `Go`
        uses: actions/setup-go@v5
        with:
          go-version: ${{ needs.go.outputs.version }}

      - name: Build core
        id: build
        run: |
          go build -v -trimpath -ldflags "-X 'github.com/metacubex/mihomo/constant.Version=${VERSION}' -s -w -buildid=" -tags "${TAGS}" -o meta.exe

      - name: Upload files to workspace
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path:
            meta*
          compression-level: 9

  push_release:
    needs:
      - cross
      - meta
    runs-on: ubuntu-latest
    env:
      VERSION: ${{needs.meta.outputs.version}}
    steps:
      - name: Clone Repository
        uses: actions/checkout@main

      - name: Download files from workspace
        uses: actions/download-artifact@v4
        with:
          path: ./tmp/

      - name: Move files
        run: |
          ls -R
          mkdir -p ./Clash.Meta-release/
          rm -rf ./Clash.Meta-release/*
          mv -f ./tmp/windows-amd64/meta* ./Clash.Meta-release/clash.meta-windows-amd64.exe
          rm -rf ./tmp* 

      - name: Commit and push
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add . && git commit -m "更新 Clash.Meta 内核 Release 版至 ${VERSION}" || exit 0
          git push -f

      - name: Purge jsDelivr CDN
        run: |
          cd ./Clash.Meta-release/ || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@main/Clash.Meta-release/${file}"
          done
