name: Update Clash Premium Latest
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".github/workflows/delete-old-workflows.yml"
      - ".github/workflows/update-adguardhome-prerelease.yml"
      - ".github/workflows/update-adguardhome-release.yml"
      - ".github/workflows/update-clash.meta-alpha.yml"
      - ".github/workflows/update-clash.meta-release.yml"
      - ".github/workflows/update-clashdashboard.yml"
      - ".github/workflows/update-clashpremium-release.yml"
      - ".github/workflows/update-singbox-prerelease.yml"
      - ".github/workflows/update-singbox-puernya.yml"
      - ".github/workflows/update-singbox-release.yml"

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@main

    - name: Zip core by `tar`
      run: |
        archs=(amd64 armv5 armv6 armv7 armv8 mips-softfloat mipsle-hardfloat mipsle-softfloat)
        for((i=0;i<8;i++));do
          chmod +x ./ClashPremium-latest/clashpremium-linux-${archs[i]}
          tar --no-same-owner -czf ./ClashPremium-latest/clashpremium-linux-${archs[i]}.tar.gz -C ./ClashPremium-latest/ ./clashpremium-linux-${archs[i]}
        done

    - name: Commit and push
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add . && git commit -m "Clash Premium 内核 Latest 版" || exit 0
        git push -f

    - name: Purge jsDelivr CDN
      run: |
        cd ./ClashPremium-latest/ || exit 1
        for file in $(ls); do
          curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@main/ClashPremium-latest/${file}"
        done
